-- MySQL Script generated by MySQL Workbench
-- Mon Jun 17 19:03:26 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema greentechdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema greentechdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `greentechdb` DEFAULT CHARACTER SET utf8mb4 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `greentechdb` ;

-- -----------------------------------------------------
-- Table `greentechdb`.`USUARIOS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `greentechdb`.`USUARIOS` ;

CREATE TABLE IF NOT EXISTS `greentechdb`.`USUARIOS` (
  `NOME` VARCHAR(250) NOT NULL,
  `BAIRRO` VARCHAR(250) NOT NULL,
  `ID` INT NOT NULL,
  `ENDERECO` VARCHAR(250) NOT NULL,
  `CIDADE` VARCHAR(250) NOT NULL,
  `CEP` VARCHAR(45) NOT NULL,
  `TELEFONE` DECIMAL(13) NOT NULL,
  `UF` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `greentechdb`.`LOGIN`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `greentechdb`.`LOGIN` ;

CREATE TABLE IF NOT EXISTS `greentechdb`.`LOGIN` (
  `LOGIN` VARCHAR(45) NOT NULL,
  `SENHA` VARCHAR(45) NOT NULL,
  `USUARIOS_ID` VARCHAR(250) NOT NULL,
  INDEX `fk_LOGIN_USUARIOS1_idx` (`USUARIOS_ID` ASC) ,
  PRIMARY KEY (`USUARIOS_ID`),
  CONSTRAINT `fk_LOGIN_USUARIOS1`
    FOREIGN KEY (`USUARIOS_ID`)
    REFERENCES `greentechdb`.`USUARIOS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `greentechdb`.`PRODUTOS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `greentechdb`.`PRODUTOS` ;

CREATE TABLE IF NOT EXISTS `greentechdb`.`PRODUTOS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(45) NOT NULL,
  `MARCA` VARCHAR(45) NOT NULL,
  `ESTADO_USO` VARCHAR(45) NOT NULL,
  `ID_PRECO` INT NOT NULL,
  `DESCRICAO` TEXT(500) NOT NULL,
  `DATA` DATE NOT NULL,
  `ID_VENDEDOR` INT NOT NULL,
  `USUARIOS_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_PRODUTOS_USUARIOS1_idx` (`USUARIOS_ID` ASC) ,
  CONSTRAINT `fk_PRODUTOS_USUARIOS1`
    FOREIGN KEY (`USUARIOS_ID`)
    REFERENCES `greentechdb`.`USUARIOS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `greentechdb`.`ANUNCIOS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `greentechdb`.`ANUNCIOS` ;

CREATE TABLE IF NOT EXISTS `greentechdb`.`ANUNCIOS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DATA_VIGENCIA` DATE NOT NULL,
  `PRECO` VARCHAR(45) NOT NULL,
  `STATUS` VARCHAR(45) NOT NULL,
  `PRODUTOS_ID` INT NOT NULL,
  `USUARIOS_ID` INT NOT NULL,
  `DESCRICAO` TEXT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_ANUNCIOS_PRODUTOS1_idx` (`PRODUTOS_ID` ASC) ,
  INDEX `fk_ANUNCIOS_USUARIOS1_idx` (`USUARIOS_ID` ASC) ,
  CONSTRAINT `fk_ANUNCIOS_PRODUTOS1`
    FOREIGN KEY (`PRODUTOS_ID`)
    REFERENCES `greentechdb`.`PRODUTOS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ANUNCIOS_USUARIOS1`
    FOREIGN KEY (`USUARIOS_ID`)
    REFERENCES `greentechdb`.`USUARIOS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `greentechdb`.`COMENTARIOS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `greentechdb`.`COMENTARIOS` ;

CREATE TABLE IF NOT EXISTS `greentechdb`.`COMENTARIOS` (
  `DATA_COMENTARIO` VARCHAR(45) NOT NULL,
  `CONTEUDO_COMENTARIO` TEXT(500) NOT NULL,
  `USUARIOS_ID` INT NOT NULL,
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ANUNCIOS_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_COMENTARIOS_USUARIOS1_idx` (`USUARIOS_ID` ASC) ,
  INDEX `fk_COMENTARIOS_ANUNCIOS1_idx` (`ANUNCIOS_ID` ASC) ,
  CONSTRAINT `fk_COMENTARIOS_USUARIOS1`
    FOREIGN KEY (`USUARIOS_ID`)
    REFERENCES `greentechdb`.`USUARIOS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_COMENTARIOS_ANUNCIOS1`
    FOREIGN KEY (`ANUNCIOS_ID`)
    REFERENCES `greentechdb`.`ANUNCIOS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `greentechdb`.`RESPOSTAS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `greentechdb`.`RESPOSTAS` ;

CREATE TABLE IF NOT EXISTS `greentechdb`.`RESPOSTAS` (
  `ID` INT NOT NULL,
  `DATA` DATE NOT NULL,
  `CONTEUDO_RESPOSTA` TEXT(500) NOT NULL,
  `COMENTARIOS_ANUNCIOS_ID` INT NOT NULL,
  `USUARIOS_ID` INT NOT NULL,
  `COMENTARIOS_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_RESPOSTAS_USUARIOS1_idx` (`USUARIOS_ID` ASC),
  INDEX `fk_RESPOSTAS_COMENTARIOS1_idx` (`COMENTARIOS_ID` ASC),
  CONSTRAINT `fk_RESPOSTAS_USUARIOS1`
    FOREIGN KEY (`USUARIOS_ID`)
    REFERENCES `greentechdb`.`USUARIOS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RESPOSTAS_COMENTARIOS1`
    FOREIGN KEY (`COMENTARIOS_ID`)
    REFERENCES `greentechdb`.`COMENTARIOS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `greentechdb`.`FOTOS_PRODUTOS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `greentechdb`.`FOTOS_PRODUTOS` ;

CREATE TABLE IF NOT EXISTS `greentechdb`.`FOTOS_PRODUTOS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ID_PRODUTOS` INT NOT NULL,
  `URL_FOTO_PRODUTO` VARCHAR(45) NOT NULL,
  `PRODUTOS_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_FOTOS_PRODUTOS_PRODUTOS1_idx` (`PRODUTOS_ID` ASC),
  CONSTRAINT `fk_FOTOS_PRODUTOS_PRODUTOS1`
    FOREIGN KEY (`PRODUTOS_ID`)
    REFERENCES `greentechdb`.`PRODUTOS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
